export const TEST_WORDS = [
  { id: 1, text: "microwave", type: "noun" },
  { id: 2, text: "fidget", type: "verb" },
  { id: 3, text: "sneaker", type: "noun" },
  { id: 4, text: "grumpy", type: "adj" },
  { id: 5, text: "buffering", type: "verb" },
  { id: 6, text: "doorknob", type: "noun" },
  { id: 7, text: "slouch", type: "verb" },
  { id: 8, text: "glitch", type: "verb" },
  { id: 9, text: "squeaky", type: "adj" },
  { id: 10, text: "deadline", type: "noun" },
  { id: 11, text: "crumple", type: "verb" },
  { id: 12, text: "sticky", type: "adj" },
  { id: 13, text: "upload", type: "verb" },
  { id: 14, text: "awkward", type: "adj" },
  { id: 15, text: "pixel", type: "noun" },
  { id: 16, text: "sprint", type: "verb" },
  { id: 17, text: "crispy", type: "adj" },
  { id: 18, text: "coffee", type: "noun" },
  { id: 19, text: "restless", type: "adj" },
  { id: 20, text: "inbox", type: "noun" },
];
